import type { ArtClass, Teacher, User, Registration } from "./types";

export const TEACHER: Teacher = {
  id: "teacher-1",
  name: "נטע הראל רימון",
};

export const CURRENT_USER: User = {
  id: "user-1",
  name: "מרים כהן",
  firstName: "מרים",
  phone: "050-1234567",
  hasSubscription: true,
};

// All dates relative to 2026-05-16 (Saturday = today, app shows from Sunday onward)
export const MOCK_CLASSES: ArtClass[] = [
  // ─── Sunday 17/05 ───
  {
    id: "cls-1",
    title: "ציור בצבעי מים",
    type: "group",
    date: "2026-05-17",
    startTime: "10:00",
    endTime: "11:30",
    duration: 90,
    teacher: TEACHER,
    capacity: 8,
    registeredCount: 4,
    waitlistCount: 0,
    status: "active",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
    description: "שיעור ציור בצבעי מים לכל הרמות. נעסוק בטכניקות בסיסיות של שכבות צבע, שטיפות ויצירת טקסטורות.",
  },
  {
    id: "cls-2",
    title: "ציור אקריליק",
    type: "group",
    date: "2026-05-17",
    startTime: "18:00",
    endTime: "19:30",
    duration: 90,
    teacher: TEACHER,
    capacity: 8,
    registeredCount: 8,
    waitlistCount: 2,
    status: "active",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription"],
    singleRegistrationEnabled: false,
    description: "ציור אקריליק — צבע נועז, תוצאות מרהיבות. נלמד ערבוב צבעים, בניית שכבות ויצירת עומק בציור.",
  },
  {
    id: "cls-3",
    title: "שיעור אישי",
    type: "private",
    date: "2026-05-17",
    startTime: "11:00",
    endTime: "12:00",
    duration: 60,
    teacher: TEACHER,
    capacity: 1,
    registeredCount: 0,
    waitlistCount: 0,
    status: "active",
    cancellationDeadlineHours: 48,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
  },

  // ─── Monday 18/05 ───
  {
    id: "cls-4",
    title: "רישום למתחילות",
    type: "group",
    date: "2026-05-18",
    startTime: "09:00",
    endTime: "10:15",
    duration: 75,
    teacher: TEACHER,
    capacity: 6,
    registeredCount: 6,
    waitlistCount: 1,
    status: "active",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
    description: "שיעור רישום לנשים שמתחילות את דרכן ביצירה. אין צורך בניסיון קודם — רק התרגשות ורצון ללמוד.",
  },
  {
    id: "cls-5",
    title: "ציור חופשי מודרך",
    type: "group",
    date: "2026-05-18",
    startTime: "19:00",
    endTime: "20:30",
    duration: 90,
    teacher: TEACHER,
    capacity: 10,
    registeredCount: 3,
    waitlistCount: 0,
    status: "active",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
    description: "שיעור חופשי עם הדרכה — כל אחת מביאה את הפרויקט שלה ונטע מלווה ומייעצת.",
  },

  // ─── Tuesday 19/05 — user is registered ───
  {
    id: "cls-6",
    title: "סדנת טבע דומם",
    type: "group",
    date: "2026-05-19",
    startTime: "10:00",
    endTime: "12:00",
    duration: 120,
    teacher: TEACHER,
    capacity: 8,
    registeredCount: 5,
    waitlistCount: 0,
    status: "active",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
    description: "סדנת ציור מיוחדת — נצייר סידור פרחים ופירות מהחיים. מוגשת כיבוד קל. אווירה נעימה ומרגיעה.",
  },
  {
    id: "cls-7",
    title: "שיעור אישי",
    type: "private",
    date: "2026-05-19",
    startTime: "14:00",
    endTime: "15:00",
    duration: 60,
    teacher: TEACHER,
    capacity: 1,
    registeredCount: 1,
    waitlistCount: 0,
    status: "active",
    cancellationDeadlineHours: 48,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
  },

  // ─── Wednesday 20/05 — one canceled ───
  {
    id: "cls-8",
    title: "ציור בצבעי מים",
    type: "group",
    date: "2026-05-20",
    startTime: "18:00",
    endTime: "19:30",
    duration: 90,
    teacher: TEACHER,
    capacity: 8,
    registeredCount: 2,
    waitlistCount: 0,
    status: "active",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
  },
  {
    id: "cls-9",
    title: "ציור אקריליק",
    type: "group",
    date: "2026-05-20",
    startTime: "10:00",
    endTime: "11:30",
    duration: 90,
    teacher: TEACHER,
    capacity: 8,
    registeredCount: 3,
    waitlistCount: 0,
    status: "canceled",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription"],
    singleRegistrationEnabled: false,
    description: "השיעור בוטל על ידי המורה.",
  },

  // ─── Thursday 21/05 — user on waitlist ───
  {
    id: "cls-10",
    title: "ציור חופשי מודרך",
    type: "group",
    date: "2026-05-21",
    startTime: "09:00",
    endTime: "10:30",
    duration: 90,
    teacher: TEACHER,
    capacity: 8,
    registeredCount: 8,
    waitlistCount: 3,
    status: "active",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription"],
    singleRegistrationEnabled: false,
  },
  {
    id: "cls-11",
    title: "שיעור אישי",
    type: "private",
    date: "2026-05-21",
    startTime: "16:00",
    endTime: "17:00",
    duration: 60,
    teacher: TEACHER,
    capacity: 1,
    registeredCount: 0,
    waitlistCount: 0,
    status: "active",
    cancellationDeadlineHours: 48,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
  },

  // ─── Sunday 24/05 — time changed, user registered ───
  {
    id: "cls-12",
    title: "ציור בצבעי מים",
    type: "group",
    date: "2026-05-24",
    startTime: "10:00",
    endTime: "11:30",
    duration: 90,
    teacher: TEACHER,
    capacity: 8,
    registeredCount: 6,
    waitlistCount: 0,
    status: "time-changed",
    previousStartTime: "09:00",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
  },
  {
    id: "cls-13",
    title: "סדנת טבע דומם",
    type: "group",
    date: "2026-05-25",
    startTime: "10:00",
    endTime: "12:00",
    duration: 120,
    teacher: TEACHER,
    capacity: 8,
    registeredCount: 2,
    waitlistCount: 0,
    status: "active",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
  },
  {
    id: "cls-14",
    title: "רישום למתחילות",
    type: "group",
    date: "2026-05-25",
    startTime: "17:00",
    endTime: "18:15",
    duration: 75,
    teacher: TEACHER,
    capacity: 6,
    registeredCount: 1,
    waitlistCount: 0,
    status: "active",
    cancellationDeadlineHours: 24,
    registrationTypes: ["subscription", "single"],
    singleRegistrationEnabled: true,
  },
];

// User's pre-existing registrations
export const MOCK_REGISTRATIONS: Registration[] = [
  {
    id: "reg-1",
    userId: "user-1",
    classId: "cls-6", // סדנת טבע דומם — 19/05 — NEXT CLASS
    type: "subscription",
    status: "registered",
    registeredAt: "2026-05-14T10:00:00Z",
  },
  {
    id: "reg-2",
    userId: "user-1",
    classId: "cls-12", // ציור בצבעי מים — 24/05 (time changed)
    type: "subscription",
    status: "registered",
    registeredAt: "2026-05-13T14:00:00Z",
  },
  {
    id: "reg-3",
    userId: "user-1",
    classId: "cls-10", // ציור חופשי מודרך — 21/05 — WAITLIST
    type: "subscription",
    status: "waitlist",
    registeredAt: "2026-05-15T09:00:00Z",
  },
];
